### ISSUE TITLE
Request Feature: Habit

### ISSUE THREAD

**Issue by zhampu** [ElliotGarbus/ChaseBlissEditor#3]

**Comment by ElliotGarbus** [comment]
I should have sometime in about a week to take a closer look at the Habit midi implementation.  I don’t have a Habit, so I would need you to commit to testing all of the features. Can you do that?

**Comment by ElliotGarbus** [comment]
@zhampu If you can commit to do the testing, I will add the Habit.  I'm closing this issue because I have not heard back from you.

**Comment by zhampu** [comment]
Hey Elliot,
Sorry I didn't saw the notification.
Sure I can do the testing :)

**Comment by ElliotGarbus** [comment]
@zhampu I'll let you know when I have something to test.  It may be a few months...
A few limitations that I'd like to make you aware of.  These limitations are due to the midi implementation of the Habit.

- Dip switches can not be modified or stored by the editor.  There is a field for you to take notes.
- Presets on the pedal can not be backed up to the computer.  The habit only received midi, it does not send midi to the editor.

**Comment by zhampu** [comment]
> @zhampu I'll let you know when I have something to test. It may be a few months... A few limitations that I'd like to make you aware of. These limitations are due to the midi implementation of the Habit.
> 
> * Dip switches can not be modified or stored by the editor.  There is a field for you to take notes.
> * Presets on the pedal can not be backed up to the computer.  The habit only received midi, it does not send midi to the editor.

Let me know when you have something to test!

**Comment by ElliotGarbus** [comment]
@zhampu I'm ready to get it out to you to test.  Windows or Mac?

![image](https://user-images.githubusercontent.com/39632979/205465958-5b58b7a2-475f-4ab8-9c39-a8996352a181.png)

**Comment by zhampu** [comment]
That was fast!
macOS.
I'm currently out of my house giving a workshop but will be back on Tuesday to test it.

**Comment by ElliotGarbus** [comment]
I suspect I'll get both the WIndows and Mac version posted before Tuesday.  I'll update the code on the release page, and let you know when it is there.

**Comment by ElliotGarbus** [comment]
I have posted the code to the release page.  Let me know how it works.

**Comment by zhampu** [comment]
It works good for me. Maybe a nice feature will be to add the Clear function (both buttons pressed). 
CC26

**Comment by ElliotGarbus** [comment]
Glad to hear it is working!  
Thanks for the suggestion on the clear button.  Just to set expectations, I don't expect I'll add the clear button.  There are a few reasons - but the biggest issues:  

- It is more work that just adding the Habit to the existing app.
- Clear is a performance feature - it not part of what goes into a preset. 
- I don't have the pedal - so it limits my interest in investing more time.

Enjoy the app and the Habit.  Happy Holidays!
